source 'https://rubygems.org'

gem 'activesupport', '7.1.2'
# gem 'bigdecimal', '1.4.4'
gem 'uri', '0.12.2'
gem 'elasticsearch-xpack', '7.17.10'
gem 'fluentd', '1.16.3'
gem 'fluent-plugin-concat', '2.5.0'
gem 'fluent-plugin-detect-exceptions', '0.0.15'
gem 'fluent-plugin-elasticsearch', '5.2.5'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.4.0'
gem 'fluent-plugin-multi-format-parser', '1.1.0'
gem 'fluent-plugin-systemd', '1.0.5'
gem 'fluent-plugin-remote_syslog', '1.1'
gem 'oj', '3.16.2'
